site_name: YAIBA-BI


########################
### Develop Settings ###
########################

watch:
  - ..


######################
### Theme Settings ###
######################

repo_url: https://github.com/earl-klutz/yaiba-bi
repo_name: YAIBA-BI

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: ja
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            members_order: source
            group_by_category: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition